version: '3'

services:
  mseauth1:
    build:
      context: .
    environment:
      RELEASE_COOKIE: 'GXFWRIRSHFIZQQDBSYLA'
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_USER: mopp
      POSTGRES_PASSWORD: mopp123
      POSTGRES_DB: mseauth
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
