version: '3'

services:
  mseauth1:
    build:
      context: .
    ports:
      - "4000:4000"
    links:
      - postgres
    volumes:
      - .:/mseauth

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_USER: mopp
      POSTGRES_PASSWORD: mopp123
      POSTGRES_DB: mseauth
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
