version: '3'

services:
  mseauth1:
    build:
      context: .
    environment:
      MIX_ENV: local
      RELEASE_COOKIE: 'GXFWRIRSHFIZQQDBSYLA'
      RELEASE_NODE: alpha@mseauth1
    depends_on:
      - postgres
    volumes:
      - .:/mseauth

  mseauth2:
    build:
      context: .
    environment:
      MIX_ENV: local
      RELEASE_COOKIE: 'GXFWRIRSHFIZQQDBSYLA'
      RELEASE_NODE: bravo@mseauth2
    depends_on:
      - postgres
    volumes:
      - .:/mseauth

  mseauth3:
    build:
      context: .
    environment:
      MIX_ENV: local
      RELEASE_COOKIE: 'GXFWRIRSHFIZQQDBSYLA'
      RELEASE_NODE: charlie@mseauth3
    depends_on:
      - postgres
    volumes:
      - .:/mseauth

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_USER: mopp
      POSTGRES_PASSWORD: mopp123
      POSTGRES_DB: mseauth
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  envoy:
    image: envoyproxy/envoy:v1.18.3
    volumes:
      - ./envoy:/etc/envoy/
    ports:
      - 8080:80

volumes:
  db:
